version: '3.9'

services:
  bookmark-container:
    image: bookmark-app:1.0
    ports:
      - 3001:3000
      
  bookmark-db:
    image: postgres:13
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env