name: NestJS CI/CD pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main

jobs:
  building:
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest

    steps:         
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 18.20.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{secrets.AWS_REGION}}
    
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build,tag and push Docker image to AWS ECR
      id: docker-image-build
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
        ECR_REPOSITORY: ${{ secrets.REPOSITORY_NAME}}
        IMAGE_TAG: latest
      run: |
        echo "Building docker image......"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing docker image to AWS ECR......"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "Done......."
        
